RUBY_COMMAND = 'ruby1.9.1'

def genzalm(zalm, options="")
  syrovy = "zalmy/"+zalm
  peceny = "generovane/"+zalm.gsub(/\.zalm/, '')+'.tex'
  preprocessor = "../nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir "generovane"
    sh "#{RUBY_COMMAND} ../#{preprocessor} #{options} ../#{syrovy}"
    chdir ".."
  end
  return peceny
end

##############
# Antifonar: kompletar

file "vystup/antifonar_kompletar.pdf" => ["vystup/antifonar_kompletar.tex"] do
  chdir "vystup"
  sh "pdflatex antifonar_kompletar"
  chdir ".."
end

cislazalmu = [4, 134, 91, 86, 143, 31, 130, 16, 88]

zalmy_syrove = cislazalmu.map {|i| "zalm"+i.to_s+".zalm"}
zalmy_pecene = cislazalmu.map {|i| "generovane/zalm"+i.to_s+".tex"}

zalmy_syrove.each_index do |i|
  genzalm zalmy_syrove[i], "--last-accent-only --linebreak-at-the-end"
end

genzalm "kantikum_nuncdimittis.zalm", "--linebreak-at-the-end"

# doxologie s jednim akcentem na polovers
genzalm "doxologie.zalm", "--last-accent-only --no-title"
# doxologie se dvema akcenty na polovers
file "generovane/doxologie_2akcenty.tex" => ['zalmy/doxologie.zalm'] do
  chdir "generovane"
  sh "ruby ../../nastroje/psalmpreprocessor.rb --no-title --output doxologie_2akcenty.tex ../zalmy/doxologie.zalm"
  chdir ".."
end
  
file "vystup/antifonar_kompletar.tex" => ["antifonar_kompletar.lytex", "kompletar_1.ly", "generovane/doxologie.tex", "generovane/doxologie_2akcenty.tex", "generovane/kantikum_nuncdimittis.tex"]+zalmy_pecene do
  sh "lilypond-book --out=vystup --pdf antifonar_kompletar.lytex"
end

file "kompletar_1.ly" => ["../kompletar.ly"] do
  sh "ruby ../nastroje/splitscores.rb --prepend-text '\\include \"spolecne_antifonar.ly\"' --remove-headers ../kompletar.ly"
end

task :kompletar => ["vystup/antifonar_kompletar.pdf"]

task :default => [:kompletar]

###############
# uvod

file 'uvod_priklady_1.ly' => ['uvod_priklady.ly'] do
  sh "#{RUBY_COMMAND} ../nastroje/splitscores.rb --prepend-text '\\include \"spolecne_antifonar.ly\"' uvod_priklady.ly"
end

file 'vystup/antifonar_uvod.tex' => ['antifonar_uvod.lytex', 'uvod_priklady_1.ly'] do
  sh 'lilypond-book --pdf --out=vystup antifonar_uvod.lytex'
end

file 'vystup/antifonar_uvod.pdf' => ['vystup/antifonar_uvod.tex'] do
  chdir 'vystup'
  sh 'pdflatex antifonar_uvod.tex'
  chdir '..'
end

task :uvod => ['vystup/antifonar_uvod.pdf']

###############
# material k responsorialnimu prednesu zalmu 136

file "generovane/zalm136responsorialni.tex" => ["zalmy/zalm136responsorialni.zalm"] do
  chdir "generovane"
  sh "ruby ../../nastroje/psalmpreprocessor.rb --no-formatting ../zalmy/zalm136responsorialni.zalm"
  chdir ".."
end

file "vystup/zalm136.tex" => ["generovane/zalm136responsorialni.tex", "zalm136noty.ly", "spolecne.tex"] do
  sh "lilypond-book --out=vystup --pdf zalm136.lytex"
end

file "vystup/zalm136.pdf" => ["vystup/zalm136.tex"] do
  cd "vystup"
  sh "pdflatex zalm136"
  cd ".."
end

#######################
# zaltar

zalmyzaltare = []

cislazalmu = %w( 95 100 67 24
                  141 142 63 149 118i 118ii 118iii 110 114
                  5 29 19b 7i 7ii 11 15
                  33 119alef 13 14 20 21
                  36 47 119beth 17i 17ii 27i 27ii
                  )

commonoptions = '--columns --lettrine'
# commonoptions = '--lettrine'
cislazalmu.each do |z|
  zalmyzaltare << genzalm("zalm"+z+".zalm", commonoptions)
end

zalmyzaltare << genzalm('kantikum_fp2.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_ef1.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_zj4.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_kol1.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_dan3i.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_1kron29.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_tob13.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_jdt16.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_benedictus.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_magnificat.zalm', commonoptions)
zalmyzaltare << genzalm('kantikum_zj19.zalm', '--no-formatting '+commonoptions)


file "antifonar_zaltar.pdf" => ['antifonar_zaltar.tex', 'kantikum_zj19.tex', 'spolecne.tex']+zalmyzaltare do
  2.times { sh "pdflatex antifonar_zaltar" }
end

task :zaltar => ["antifonar_zaltar.pdf"]