# encoding: utf-8

task :all => [:kompletar, :zaltar, :cteni, :festzaltar, :nedele, :triduum]
task :default => [:all]

RUBY_COMMAND = 'ruby' # was: 'ruby1.9.1'

def genzalm(zalm, options="", adresar='generovane/')
  wd = Dir.pwd
  syrovy = wd+"/zalmy/"+zalm
  peceny = adresar+zalm.gsub(/\.zalm/, '')+'.tex'
  preprocessor = wd+"/../nastroje/psalmpreprocessor.rb"
  file peceny => [syrovy, preprocessor] do
    chdir adresar
    sh "#{RUBY_COMMAND} #{preprocessor} #{options} #{syrovy}"
    chdir wd
    sh "vlna #{peceny}"
  end
  return peceny
end

def genspojenyzalm(zdroje, vysledek, options='', adresar='generovane/')
  wd = Dir.pwd
  syrove = zdroje.map {|zalm| wd+"/zalmy/"+zalm }
  peceny = adresar+vysledek
  preprocessor = wd+"/../nastroje/psalmpreprocessor.rb"
  file peceny => syrove+[preprocessor] do
    chdir adresar
    sh "#{RUBY_COMMAND} #{preprocessor} #{options} --output #{vysledek} --join #{syrove.join " "}"
    chdir wd
    sh "vlna #{peceny}"
  end
  return peceny
end

task "test_lilypondbook_version" do
  v = `lilypond-book --version`.rstrip
  if v !~ /^2\.1[67]/ then
    STDERR.puts
    STDERR.puts "!!! Expect problems. Compilation of notated parts of the antiphonal works well only with lilypond-book 2.15.x !!! [#{v} found]"
    STDERR.puts
  else
    puts "LilyPond version [#{v}] OK."
  end
end

Rake::Task["test_lilypondbook_version"].execute

def make_dirs(struc)
  wd = Dir.pwd
  
  struc.each_key do |k|
    if ! FileTest.directory?(k) then
      Dir.mkdir k
    end
    Dir.chdir k
    make_dirs struc[k]
    Dir.chdir '..'
  end
end

# create directory structure used by the tasks
dirs = { 'generovane' => {'kompletar' => {},
                                                'nedele' => {},
                                                'zaltar' => {},
                                                'svatecnizaltar' => {},
                                                'triduum' => {},
    'nespornizpevy' => {}},
              'vystup' => {}}
make_dirs dirs

##############
# promenne pouzivane vice ulohami - argumenty pro program psalmpreprocessor.rb
$o_canticletitle = " --pretitle \"kantikum\\\\\\\\ \""
$o_doxology = " --append \"\\nopagebreak Sláva Otci.\""
$o_doxology_full = ' --append "' + File.read('zalmy/doxologie.zalm') + '"'
$o_columns = " --columns"
$o_warnmarks = ' --mark-short-verses'

$commonoptions_withoutdoxology = "--lettrine --dashes --no-paragraph --guillemets"
$commonoptions = $commonoptions_withoutdoxology+$o_doxology
$canticleoptions = $commonoptions+$o_canticletitle

# prikaz pouzivany ke zpracovani vsech extrahovanych not pro
# nedelni antifonar.
# na konec se pouze pripoji (pripadne dalsi volby a) jmeno souboru ke zpracovani.
$splitscores_command = "#{RUBY_COMMAND} -I ../nastroje "+ 
          "../nastroje/splitscores.rb "+
                        "--prepend-text '\\include \"../../spolecne_antifonar.ly\"\n \\include \"../../../dilyresponsorii.ly\"' "+
                        "--remove-headers "+
                        "--mode-info "+
                        "--ids "

desc "Delete LilyPond-Book's stored snippets"
task :snipclean do
  cd 'vystup'
  sh 'rm -rf tmp*'
  sh 'rm -rf snippet*'
  Dir['*'].each {|f| sh "rm -rf #{f}" if f.size == 2 }
  cd '..'
end

require './rakefile_uplne.rb'
require './rakefile_vyberova.rb'
require './rakefile_zaltare.rb'
require './rakefile_mimorady.rb'
