# encoding: utf-8

# labelpsalm.rb

# for: antifonar_zaltar

# in a LaTeX source puts a \label in front of each psalm/canticle.
# The label contains an order number of occurrence of the respective text.

inputf = ARGV.shift
o = STDOUT

texts = {}

o.puts "% GENERATED by #{__FILE__} from #{inputf}"
o.puts

File.open(inputf).each_line do |l|
  match = /\\(zalm|kantikum)\{([^\}]+)\}/.match(l)
  if match.nil? then
    o.puts l
    next
  end

  text_label = match[1][0] + match[2]

  unless texts.include? text_label
    texts[text_label] = 0
  end
  texts[text_label] += 1

  if texts[text_label] == 1 then
    o.print "\\label{#{text_label}}"
  end
  o.print "\\label{#{text_label}:#{texts[text_label]}}"
  o.puts l
end
