RUBY_COMMAND = 'ruby1.9.1'

$splitscores_command = "#{RUBY_COMMAND} -I ../nastroje "+ 
          "../nastroje/splitscores.rb "

def task_scoresplit(scf)
  i = scf.rindex('.ly')
  wanted = scf[0..i-1]+'_1'+scf[i..-1]
  wanted = File.basename(wanted)
  puts wanted
  file wanted => [scf] do |t|
    sh $splitscores_command+scf
  end
end

task_scoresplit '../responsoria.ly'
task_scoresplit '../advent_responsoria.ly'
task_scoresplit '../pust_responsoria.ly'
task_scoresplit '../velikonoce_responsoria.ly'

file 'responsorial.pdf' => ['responsorial.ly',
                                          'responsoria_1.ly',
                                          'advent_responsoria_1.ly',
                                          'pust_responsoria_1.ly',
                                          'velikonoce_responsoria_1.ly'] do
  sh "lilypond responsorial.ly"
end

task :default => ['responsorial.pdf']