RUBY_COMMAND = 'ruby1.9.1'

$splitscores_command = "#{RUBY_COMMAND} -I ../nastroje "+ 
          "../nastroje/splitscores.rb "

def task_scoresplit(scf, outputname='', options='')
  i = scf.rindex('.ly')
  if outputname == '' then
    wanted = scf[0..i-1]+'_1'+scf[i..-1]
    wanted = File.basename(wanted)
  else
    wanted = outputname
  end
  file wanted => [scf] do |t|
    sh $splitscores_command+options+' '+scf
  end
end

task_scoresplit '../responsoria.ly', 'responsoria_1ne-rch.ly', '--ids'
task_scoresplit '../advent_responsoria.ly'
task_scoresplit '../vanoce_narozenipane.ly', 'vanoce_narozenipane_narozeni-rch-resp.ly', '--ids'
task_scoresplit '../vanoce_zjevenipane.ly', 'vanoce_zjevenipane_epifanie-rch-resp.ly', '--ids'
task_scoresplit '../pust_responsoria.ly'
task_scoresplit '../velikonoce_responsoria.ly'
task_scoresplit '../antifony/tyden1_1nedele.ly', 'tyden1_1nedele_1ne-resp.ly', '--ids'
task_scoresplit '../antifony/tyden2_1nedele.ly', 'tyden2_1nedele_1ne-resp.ly', '--ids'

file 'responsorial.pdf' => ['responsorial.ly',
                                          'responsoria_1ne-rch.ly',
                                          'advent_responsoria_1.ly',
                                          'vanoce_narozenipane_narozeni-rch-resp.ly',
                                          'vanoce_zjevenipane_epifanie-rch-resp.ly',
                                          'pust_responsoria_1.ly',
                                          'velikonoce_responsoria_1.ly',
                                          'tyden1_1nedele_1ne-resp.ly',
                                          'tyden2_1nedele_1ne-resp.ly'] do
  sh "lilypond responsorial.ly"
end

task :default => ['responsorial.pdf']

task :clean do
  sh "rm *_*.ly"
  sh "rm *.pdf"
end