file "manual.pdf" => ['manual.tex', 
                      'stavebnikameny.tex',
                      'otevreneotazky.tex'] do |t|
  2.times { sh "pdflatex #{t.prerequisites.first}" }
end

task :default => ['manual.pdf']
